#!/usr/bin/perl

use warnings;
use strict;
use 5.010;

use utf8;

use Cwd             'abs_path';
use File::Slurp     'slurp';
use File::Find      'find';
use File::Path      qw(make_path);
use Scalar::Util    'blessed';
use File::Basename  qw(fileparse basename dirname);
use JSON::XS        qw(decode_json);

use IO::Async::Function;
use IO::Async::Loop;
use Getopt::Long::Descriptive;
